#!/bin/sh

notification(){
	notify-send "Now Playing Radio ☕️🎶"
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill\n"
    printf "7. Synthwave Club\n"
    printf "8. OraclesFM: Synthwave\n"
    printf "9. Radio Santangelo Retrowave\n"
    printf "10. Black Metal Rituals Radio"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification ;
				mpv "https://play.streamafrica.net/lofiradio"
			break
			;;
		2)
			notification ;
				mpv "http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		3)
			notification ;
				mpv "http://stream.zeno.fm/f3wvbbqmdg8uv"
			break
			;;
		4)
			notification ;
				mpv "http://stream.zeno.fm/0r0xa792kwzuv"
			break
			;;
		5)
			notification ;
				mpv "https://live.radiospinner.com/lofi-hip-hop-64"
			break
			;;
		6)
			notification ;
				mpv "https://media-ssl.musicradio.com/SmoothChill"
			break
			;;
        7)
            notification ;
                mpv "https://stream.zeno.fm/ay8y2c7q9c0uv"
            break
            ;;
        8)
            notification ;
                mpv "https://stream.zeno.fm/n4pvd6q68f8uv"
            break
            ;;
        9)
            notification ;
                mpv "https://stream.zeno.fm/xh5q3sm1vd0uv"
            break
            ;;
        10)
            notitfication ;
                mpv "https://stream.zeno.fm/t9wdzppre5zuv"
            break
            ;;

	esac
}

pkill -f http || main
