#!/bin/bash

current_state=0

while true; do
    state=$(cat /proc/acpi/button/lid/LID/state | grep -ioP "\w*$")
    echo -e "$state: $current_state"
    if [[ $state == "closed" ]] && [[ $current_state == 0 ]]; then
        echo "Lockscreen"
        /usr/bin/i3lock suspend
        current_state=1
    elif [[ $state == "open" ]]; then
        echo "Do not lockscreen"
        current_state=0
    fi
    sleep 1
done
