#!/bin/sh

BLANK='#282828'
CLEAR='#282828'
DEFAULT='#fabd2f'
TEXT='#ebdbb2'
WRONG='#fb4934'
TIPING='#8ec07c'
VERIFYING='#b8bb26'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$TIPING        \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 1                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%a,%d %m %Y"     \
--keylayout 1                \
--radius 110                 \
--ring-width 5               \
--noinput-text "No input"    \
--verif-text "Verifying..."  \
--wrong-text "Wrong!"        \
--ignore-empty-password
